In [1]:
# Pandas is used for data manipulation
import pandas as pd# Read in data and display first 5 rows
df = pd.read_csv('star_classification.csv')
df.head(100)

,obj_ID,alpha,delta,u,g,r,i,z,run_ID,rerun_ID,cam_col,field_ID,spec_obj_ID,redshift,plate,MJD,fiber_ID,class
0,1.237660e+18,135.689107,32.494632,23.87882,22.27530,20.39501,19.16573,18.79371,3606,301,2,79,6.543780e+18,0.634794,5812,56354,171,GALAXY
1,1.237660e+18,144.826101,31.274185,24.77759,22.83188,22.58444,21.16812,21.61427,4518,301,5,119,1.176010e+19,0.779136,10445,58158,427,GALAXY
2,1.237660e+18,142.188790,35.582444,25.26307,22.66389,20.60976,19.34857,18.94827,3606,301,2,120,5.152200e+18,0.644195,4576,55592,299,GALAXY
3,1.237660e+18,338.741038,-0.402828,22.13682,23.77656,21.61162,20.50454,19.25010,4192,301,3,214,1.030110e+19,0.932346,9149,58039,775,GALAXY
4,1.237680e+18,345.282593,21.183866,19.43718,17.58028,16.49747,15.97711,15.54461,8102,301,3,137,6.891860e+18,0.116123,6121,56187,842,GALAXY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1.237670e+18,348.335815,25.685581,23.93912,22.92743,21.78178,20.69582,19.83773,4822,301,3,437,8.675070e+18,0.686254,7705,57332,35,GALAXY
96,1.237670e+18,42.048515,32.466019,21.80150,18.61152,17.18664,16.54847,16.14959,5934,301,4,155,3.614190e+18,0.000037,3210,54876,173,STAR
97,1.237660e+18,169.417237,7.719850,25.08139,22.03635,21.83119,21.71758,21.24758,3841,301,5,31,6.045070e+18,0.000266,5369,56272,422,STAR
98,1.237660e+18,243.498908,4.309792,21.23949,20.39086,20.35097,20.25421,19.90627,3910,301,4,222,5.412460e+18,2.290692,4807,55687,940,QSO
99,1.237680e+18,44.374089,3.017933,25.76758,22.40062,20.49454,19.55738,19.04092,7675,301,6,164,4.793200e+18,0.524215,4257,55480,889,GALAXY

In [2]:
import pandas as pd
import numpy as np
import graphviz
import pydotplus
import matplotlib.image as mpimg
import io
import random

from matplotlib import pyplot as plt
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn import preprocessing, tree, datasets
from dtreeviz.trees import dtreeviz

In [3]:
pd.set_option('display.max_rows', 10)
random.seed(24)

In [4]:
X = df.drop('class', axis=1)
y = df['class']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=24)

In [5]:
classifier = tree.DecisionTreeClassifier(class_weight=None, 
                                         criterion='entropy', 
                                         max_depth=3,
                                         max_features='auto', 
                                         splitter='best', 
                                         random_state=24)
model = classifier.fit(X_train, y_train)
model.score(X_test, y_test)

c:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\tree\_classes.py:298: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'`.
  warnings.warn(

0.94532

In [6]:
features_dict = {'feature_importances': classifier.feature_importances_, 'feature_names': X_train.columns}

pd.DataFrame(features_dict).sort_values(by='feature_importances', ascending=False).head(19)

    feature_importances feature_names
13             0.976452      redshift
4              0.014653             g
14             0.008509         plate
6              0.000386             i
0              0.000000        obj_ID
..                  ...           ...
7              0.000000             z
5              0.000000             r
3              0.000000             u
2              0.000000         delta
16             0.000000      fiber_ID

[17 rows x 2 columns]

In [7]:
df2 = df
df2.drop(columns=['fiber_ID','delta','u','r','z','obj_ID','run_ID','rerun_ID','cam_col','field_ID','spec_obj_ID','MJD','g','i','plate','alpha'],inplace=True)
df2.head(2)

   redshift   class
0  0.634794  GALAXY
1  0.779136  GALAXY

In [8]:
X2 = df2.drop('class', axis=1)
y2 = df2['class']

X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, random_state=24)

In [9]:
classifier2 = tree.DecisionTreeClassifier(class_weight=None, 
                                         criterion='entropy', 
                                         max_depth=3,
                                         max_features='auto', 
                                         splitter='best', 
                                         random_state=24)
model2 = classifier2.fit(X_train2, y_train2)
model2.score(X_test2, y_test2)

c:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\tree\_classes.py:298: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'`.
  warnings.warn(

0.94924

In [10]:
def predict_single_label( 
                         redshift
                      
                         ):
    y_predict = classifier2.predict([[redshift]])[0]
    return y_predict

In [19]:
user = input('enter red shift value from 0 to 1')
test1= predict_single_label(user)
test1

c:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

'STAR'